### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Danappelxx** [Danappelxx/SwiftMongoDB#10]
I'm working on it - I'm having some issues with dependent modulemaps, but I'll figure it out. Obviously this goes along with #9.

I'm thinking of adding [SwiftFoundation](https://github.com/PureSwift/SwiftFoundation) as a dependency to handle JSON for me, otherwise I'm relying on Foundation, which hasn't been implemented yet. It shouldn't be an issue since SwiftFoundation supports both SPM and Carthage.

**Comment by Danappelxx** [comment]
Having some issues but I got it to build on Ubuntu 15.10. My progress so far is on the `linux` branch of this repository - clone, install SwiftFoundation dependencies, run `swift build` (it should fail), run `./build.sh`, and a binary should appear at `.build/debug/SwiftMongoDB`. Unfortunately I'm getting segfaults - I haven't looked in detail as to why they're happening, though.

**Comment by Danappelxx** [comment]
Fixed segfaults; haven't figured out how to run tests yet.

**Comment by Danappelxx** [comment]
With the new changes to SPM and the introduction of [BinaryJSON](https://github.com/pureswift/binaryjson), I finally got the library to build and run on Linux. I tested some basic stuff such as querying and inserting, but I have yet to run the test suite.

**Comment by justmark** [comment]
I'm getting the same build errors as before - are you running a build script as you were before?  If so, can you share that?

**Comment by Danappelxx** [comment]
My bad. Instead of just `swift build`, run `swift build -Xcc -I/usr/local/include/libbson-1.0/`. What that does is add `libbson` to the include paths. The folks behind SPM are working on a better solution but this is a good enough workaround for me for now.

**Comment by justmark** [comment]
No worries - that worked.  Will take it for a spin now!

**Comment by Danappelxx** [comment]
Got it working! I set the default branch to Linux as I'm not ready to merge it into master yet but work will be done here.
