### ISSUE TITLE
.find() only return 1 record

### ISSUE THREAD

**Issue by tennisplayer88** [Danappelxx/SwiftMongoDB#12]
Good package, however, when I use below code, it only return one record. My collection have at least 100 records.
And also have invalid type on the MongoDB "created_at" field?
Anything i missed?
Thanks.

   let results = try subjects.find()
            for result in results {
                let skData = result.data
                print(skData["_id"])
            }

---

found oid: 5663e13cab9f9e8e05385f42
found string: 2366 0959 with key: PhoneNo
found string: info@uniServe.com.hk with key: Email
found string: http://www.uniserve.com.hk with key: Website
invalid type  <--- this should be "created_at"

**Comment by Danappelxx** [comment]
I'll look into single document issue - I've never seen that one. For dates, you need to specify them in the query as such:

``` swift
let query = ["created_at": ["$date": time_since_1970 ]
```

Also, it would be helpful to know what version you're using.

Thanks for the report!

**Comment by Danappelxx** [comment]
I'm unable to replicate your issue with the head of the master branch. Can you open the SwiftMongoDB project and run the test (with `mongod` running) and see if any of them fail?

**Comment by Danappelxx** [comment]
I'm going to close this now due to inactivity, If the issue still happens, feel free to reopen.

**Comment by agerasimchuk** [comment]
Hi Dan - ran into this issue as well - any updates?

**Comment by Danappelxx** [comment]
Well, it depends. What version are you using and on what platform? Keep in mind that <v0.4 is not really supported as it had some major bugs.

**Comment by agerasimchuk** [comment]
I've installed via CocoaPods (https://cocoapods.org/pods/SwiftMongoDB), which seems to point to an older version.  Unfortunately I cannot install via the Swift Package Manager, as the system requirement to install the Development Snapshot is to have El Capitan, and my company is blocking it temporarily, so I am on OS X Yoseite, 10.10.5.   What is the best way to install swiftmongoDB you would recommend?

**Comment by Danappelxx** [comment]
Oh man, the cocoapods version is _so_ old and broken... Im not sure what you tell you. I can't really support cocoapods anymore. I think your best option here is to either run Linux in a vm or docker, or alternatively take a look at [MongoKitten](https://github.com/PlanTeam/MongoKitten), which is pure swift so you might have a better shot there.
