### ISSUE TITLE
find() function returning weird results

### ISSUE THREAD

**Issue by AAFFTechnologies** [Danappelxx/SwiftMongoDB#13]
Hello! 

Love the library, good job! When using the find() function on my mongo db, it either returns an incorrect amount of items, or it returns duplicate of one item and overwrites another item, still returning an incorrect number of items. Ive attached screenshots to sort out confusion. 

<img width="968" alt="screen shot 2015-12-30 at 10 44 16 am" src="https://cloud.githubusercontent.com/assets/14142372/12055468/7162928a-aee2-11e5-831e-b439270b6970.png">

<img width="803" alt="screen shot 2015-12-30 at 10 44 50 am" src="https://cloud.githubusercontent.com/assets/14142372/12055467/715f7bd6-aee2-11e5-8025-77c6c3c6ae7f.png">

For instance when querying my DB i should see whats in the first picture, but instead i get back whats in the second. Very peculiar. Thoughts?

Thanks!

**Comment by Danappelxx** [comment]
Wow, that's super strange. I'll definitely look into it as soon as I get the time.

What worries me is that my tests _should_ be catching behavior like this and they haven't been failing. Could you clone the branch and run the tests? Thanks.

**Comment by fritza** [comment]
There’s a reproducing case at fritza/SMDB-repro. Should be straightforward from the source and the README.

**Comment by Danappelxx** [comment]
Thanks for the super in-depth analysis! I took a look and at first glance I noticed you're using cocoa pods. Cocoapods is not supported anymore and that podspec is from a _very_ long time ago. The bug has since been fixed and a refactor has been done. I recommend you use Carthage instead.

Let me know if you need further help!

**Comment by Danappelxx** [comment]
Ping? Seems like the issue should be resolved...

**Comment by fritza** [comment]
How embarrassing, beg pardon. Yes, the version from Carthage works fine. And boy was the pod out-of-date. Is there a way to take it down? I was confused.

**Comment by Danappelxx** [comment]
I'll take a look - there should be. Glad you got it resolved!

**Comment by Danappelxx** [comment]
Looks like CocoaPods' trunk api is broken right now... not too surprised but definitely annoyed.
