### ISSUE TITLE
MongoClient is not defined

### ISSUE THREAD

**Issue by owldrak** [Danappelxx/SwiftMongoDB#16]
Hi,

Installed via pods,

trying to follow guides -  throws undefined.

If I use it as MongoDB - it works, is there some change missing in guides?

**Comment by Danappelxx** [comment]
Hey. Cocoapods is no longer supported as of 5 or so months ago. Use Carthage instead :)

**Comment by owldrak** [comment]
oh, crap :) thx
btw, is it  possible to use this library for user auth or its better to stick with Alamofire ?

**Comment by Danappelxx** [comment]
I would recommend doing whatever helps you finish your mvp, but eventually I would most definitely not recommend using this library in your app and instead interfacing with your database through a backend. It's a bad idea in multiple ways to talk directly to the database.

Anyway, I'm to go ahead and close this issue :)
