### ISSUE TITLE
BSON.Number rawValue initializer always returns `nil`

### ISSUE THREAD

**Issue by svanimpe** [Danappelxx/SwiftMongoDB#18]
The following prints `nil`:

```
let bsonNumber = BSON.Number(rawValue: 11)
print(bsonNumber)
```

This is likely the reason (from `BSON.swift`):

```
    public init?(rawValue: Any) {

        if let value = rawValue as? Bool            { self = .Boolean(value) }
        if let value = rawValue as? Int32           { self = .Integer32(value) }
        if let value = rawValue as? Int64           { self = .Integer64(value) }
        if let value = rawValue as? Swift.Double     { self = .Double(value)  }

        return nil
    }
```

I am running the March 1 build of Swift on Ubuntu 15.10

**Comment by svanimpe** [comment]
At first I thought this was simply a matter of missing return statements in the ifs, but that's not all. If the `rawValue` is an `Int`, none of the tests succeed. I've used the following as a workaround:

```
    public init?(rawValue: Any) {

        if let value = rawValue as? Bool            { self = .Boolean(value); return }
        if let value = rawValue as? Int32           { self = .Integer32(value); return }
        if let value = rawValue as? Int64           { self = .Integer64(value); return }
        if let value = rawValue as? Int             { self = .Integer64(Int64(value)); return }
        if let value = rawValue as? Swift.Double     { self = .Double(value); return  }

        return nil
    }
```

**Comment by Danappelxx** [comment]
I believe Int is simply a typealias to either Int64 or Int32 depending on the system, so the fact that those typecasts fail is quite strange. Again, this unexpected behavior stems from non-ObjC swift environment not supporting some forms of typecasting. I'll see if there are any workarounds but for now it's probably safest to remove the rawValue initializer.

**Comment by Danappelxx** [comment]
Fixed, though I don't like that solution...
