### ISSUE TITLE
[Carthage] xcodebuild timed out

### ISSUE THREAD

**Issue by cerebralmisfire** [Danappelxx/SwiftMongoDB#26]
This might be a Carthage issue, but I get this:

**\* Checking out SwiftMongoDB at "0.4.0"
**\* xcodebuild output can be found in /var/folders/25/4d9xp1cs27v5gpzb0yj6q42c0000gn/T/carthage-xcodebuild.xtAhgK.log
xcodebuild timed out while trying to read SwiftMongoDB.xcodeproj 😭

Cheers

**Comment by Danappelxx** [comment]
Looks like it. What's your cartfile?

**Comment by cerebralmisfire** [comment]
Only one line, really.

github "Danappelxx/SwiftMongoDB" ~> 0.4

**Comment by Danappelxx** [comment]
Ah, 0.4 is not compatible with Carthage yet - I should get on that. For now, try using `github "Danappelxx/SwiftMongoDB" "master"`.

**Comment by cerebralmisfire** [comment]
Worked like a charm, with warnings on compile but did the job!

**Comment by Danappelxx** [comment]
:smiley: I'll let you know when I update it.
