### ISSUE TITLE
OS supported?

### ISSUE THREAD

**Issue by TofPlay** [Danappelxx/SwiftMongoDB#33]
Hi. It's not clear what OS are supported.
You can add on top of your readme.md 
![Platform](https://img.shields.io/badge/platform-Linux%2C%20OSX%2C%20iOS-lightgrey.svg)
Check [Shield.io](http://shields.io/) to make your own

**Comment by Danappelxx** [comment]
Great idea! I was just thinking of how to discourage people trying to use it on iOS 🙂

I'll add it once I get to a computer.

**Comment by TofPlay** [comment]
Just a detail: Usually badges are just below the title 😉

**Comment by Danappelxx** [comment]
Done 😃
