### ISSUE TITLE
Error parsing document that contains _id without $oid

### ISSUE THREAD

**Issue by matfur92** [Danappelxx/SwiftMongoDB#4]
``` swift
let coll = MongoCollection.init(collectionName: collection, client: mongoClient!)
do{
    documents = try coll.find()
}catch ...
```

In this piece of code I have run-time exception :
`Invalid input string MetaDataController, looking for 2`
Error in :

``` swift
private func initBSON() {
    try! MongoBSONEncoder(data: self.data).copyTo(self.BSONRAW)
}
```

parsing 
`{ "_id" : "MetaDataController", "metaDataEnabled" : true }`
that is a document of `objectlabs-system`collection. 
This collection is one of default collections of MongoLab database.

Same error with `objectlabs-system.admin.collections`collection, for example with `{ "_id" : "prova", "viewMode" : "list" }`.

I think that the problem is _id key. It could contains everything and not only [ "$oid" : "...." ]

**Comment by Danappelxx** [comment]
I tried fighting with this [here](https://github.com/Danappelxx/SwiftMongoDB/blob/master/swiftMongoDB/MongoDocument.swift#L40), but the logic isn't perfect. I'll clean it up when I have the time.

**Comment by matfur92** [comment]
Thanks a lot for the modify! I'm going to test it ;)

**Comment by matfur92** [comment]
Nothing change with your fix.
Then I fixed code disabling side effect in MongoDocument init. 

``` swift
public init(let data: DocumentData) throws {
    self.documentData = data
    self.initBSON()
}
```

In this way, you don't modify user data. This is very important in a library that anyone can use! You can't add or modify properties of a document!

Is good to have others convenience init, but default must not have side effect in my opinion ;)

**Comment by Danappelxx** [comment]
Hmm... The problem I was solving is that mongo requires _id to be `[_id : [ $oid : string ]` instead of just '[_id : string]`. I agree that I shouldn't be modifying the data but I don't think I've ever written $oid in other libraries, so I don't see why not in this case.

**Comment by matfur92** [comment]
_id could be anything, like in MongoLab system collection example that I reported, see yourself with a free account on MongoLab ;) 
_id isn't required on every document ;)

**Comment by Danappelxx** [comment]
Alrighty then 👍
