### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by Danappelxx** [Danappelxx/SwiftMongoDB#9]
Working on it...

**Comment by Danappelxx** [comment]
Having some issues with mongoc & libbson...

Relevant issue: [SR-145](https://bugs.swift.org/browse/SR-145)

**Comment by matteocrippa** [comment]
@Danappelxx did you test this? https://bugs.swift.org/browse/SR-145?focusedCommentId=11362&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11362

**Comment by Danappelxx** [comment]
The official workaround (a little different than that) has been merged into the latest snapshot but I haven't gotten around to testing it out yet.

**Comment by Danappelxx** [comment]
I'm happy to say that we now have SPM support! An example Package.swift:

``` swift
import PackageDescription

let package = Package(
    name: "<package name>",
    dependencies: [
      .Package(url: "https://github.com/danappelxx/SwiftMongoDB", majorVersion: 0, minor: 3)
    ]
)
```

then simply run `swift build -Xcc -I/usr/local/include/libbson-1.0/` and a binary should pop up under `.build/debug/<package name>`.

Here is a small example program which will list the available databases, connect to the first one, make a collection, insert a document, and print that document:

``` swift
import SwiftMongoDB

do {

    let client = try MongoClient(host: "localhost", port: 27017)
    print("up and running!")

    let names = try client.getDatabaseNames()
    print(names)

    guard let name = names.first else { print("Need at least one database!"); return }
    print(name)

    let database = MongoDatabase(client: client, name: name)

    let collection = MongoCollection(name: "test", database: database)

    try collection.insert([
        "name": .String("dan"),
    ])

    let documents = try collection.find()

    print(documents.map { $0.data })

} catch {
    print(error)
}
```

You can paste that into your `main.swift` and run the `swift build` command (with the flags given above) and you'll have yourself a nice collection-inserter :). Make sure you have the mongodb daemon running first, though.

Let me know if you have questions!

**Comment by svanimpe** [comment]
This example didn't work for me. I got the executable built, but running it results in the following error:
`error while loading shared libraries: libbson-1.0.so.0: cannot open shared object file: No such file or directory`
That file does exist, in `/usr/local/lib/`.

**Comment by Danappelxx** [comment]
Are you on OSX or Linux? I'll look into it...

**Comment by svanimpe** [comment]
I'm using Linux (Ubuntu)

**Comment by Danappelxx** [comment]
What Swift snapshot are you using? I think there might be issues with that.

**Comment by svanimpe** [comment]
I'm using the February 8 build.

**Comment by Danappelxx** [comment]
Try adding these flags: `swift build -Xcc -I/usr/local/include/libbson-1.0 -Xlinker -lbson-1.0`.

**Comment by svanimpe** [comment]
The issue remains :(
BTW: not sure if you got that, but it's not the build that fails (that works, thanks to the flags), it's actually running the executable that fails.

**Comment by svanimpe** [comment]
Running the executable with LD_LIBRARY_PATH=/usr/local/lib in front of it fixes the issue. Turns out I had to run `ldconfig` after installing the MongoDB C Driver.

**Comment by Danappelxx** [comment]
Ah, glad you got that sorted. I was afraid this is another SPM bug.
